from .page_replacement_algorithm import PageReplacementAlgorithm
from .fifo_replacement import FIFOPageReplacement
from .optimal_replacement import OptimalPageReplacement
from .lru_replacement import LeastUsedPageReplacement
